server:
  port: 8888
  servlet:
    context-path: /gen-order
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3307/hxh_platform
    url: jdbc:mysql://127.0.0.1:3306/hxh_platform
    username: root
#    password: hxh2023@
    password: 123456
feign:
  okhttp:
    enabled: true
  system:
    url: http://hxh.aidigifts.com/